title: Jekyll Elite
description: A modern Jekyll theme for the web of 2026.
url: https://kamrullab.github.io
baseurl: /jekyll-elite
lang: en
repository: kamrullab/jekyll-elite
author:
  name: KAMRUL HOSSAIN
  url: https://github.com/kamrullab

theme_mode: system
show_excerpts: true

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

feed:
  path: feed.xml

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-elite.gemspec
  - Rakefile
  - README.md
  - CONTRIBUTING.md
  - SECURITY.md
  - CHANGELOG.md
  - vendor
